// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkdnfzlxgpijjqhnecqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrZG5memx4Z3BpampxaG5lY3FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzMwNTcsImV4cCI6MjA2NjI0OTA1N30.xGpQdDypF9kf9ThNQirHTQ3h-RhLb21HzVUahl_QoEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});