// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzqdgegtyvlzqbjgzjpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6cWRnZWd0eXZsenFiamd6anB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDA3NTYsImV4cCI6MjA2NzExNjc1Nn0.ojugGpvqPHtFNk_-6WfJeIMJQnVkiIVThrC7wT9DYaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});